### Weekday Mini Drill
Gavin Qu 12-04-2025

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mohankrishnathalla/diabetes-health-indicators-dataset")

print("Path to dataset files:", path)
# diabetes_dataset.csv: /Users/gavinqu/.cache/kagglehub/datasets/mohankrishnathalla/diabetes-health-indicators-dataset/versions/1/diabetes_dataset.csv

/Users/gavinqu/dev/predoc/venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: /Users/gavinqu/.cache/kagglehub/datasets/mohankrishnathalla/diabetes-health-indicators-dataset/versions/1

In [2]:
import pandas as pd
import numpy as np
import os

df = pd.read_csv("/Users/gavinqu/.cache/kagglehub/datasets/mohankrishnathalla/diabetes-health-indicators-dataset/versions/1/diabetes_dataset.csv")

print(f"shape of the df is: {df.shape}")
print(f"The first five rows of the df: {df.head(5)}")
print(f"Describe the dataset:\n {df.describe().T}")
print(f"df.info: {df.info()}")

shape of the df is: (100000, 31)
The first five rows of the df:    age  gender ethnicity education_level  income_level employment_status  \
0   58    Male     Asian      Highschool  Lower-Middle          Employed
1   48  Female     White      Highschool        Middle          Employed
2   60    Male  Hispanic      Highschool        Middle        Unemployed
3   74  Female     Black      Highschool           Low           Retired
4   46    Male     White        Graduate        Middle           Retired

  smoking_status  alcohol_consumption_per_week  \
0          Never                             0
1         Former                             1
2          Never                             1
3          Never                             0
4          Never                             1

   physical_activity_minutes_per_week  diet_score  ...  hdl_cholesterol  \
0                                 215         5.7  ...               41
1                                 143         6.7  ...               55
2                                  57         6.4  ...               66
3                                  49         3.4  ...               50
4                                 109         7.2  ...               52

   ldl_cholesterol  triglycerides  glucose_fasting  glucose_postprandial  \
0              160            145              136                   236
1               50             30               93                   150
2               99             36              118                   195
3               79            140              139                   253
4              125            160              137                   184

   insulin_level  hba1c  diabetes_risk_score  diabetes_stage  \
0           6.36   8.18                 29.6          Type 2
1           2.00   5.63                 23.0     No Diabetes
2           5.07   7.51                 44.7          Type 2
3           5.28   9.03                 38.2          Type 2
4          12.74   7.20                 23.5          Type 2

   diagnosed_diabetes
0                   1
1                   0
2                   1
3                   1
4                   1

[5 rows x 31 columns]
Describe the dataset:
                                        count        mean        std     min  \
age                                 100000.0   50.120410  15.604600   18.00
alcohol_consumption_per_week        100000.0    2.003670   1.417779    0.00
physical_activity_minutes_per_week  100000.0  118.911640  84.409662    0.00
diet_score                          100000.0    5.994787   1.780954    0.00
sleep_hours_per_day                 100000.0    6.997818   1.094622    3.00
screen_time_hours_per_day           100000.0    5.996468   2.468406    0.50
family_history_diabetes             100000.0    0.219410   0.413849    0.00
hypertension_history                100000.0    0.250800   0.433476    0.00
cardiovascular_history              100000.0    0.079200   0.270052    0.00
bmi                                 100000.0   25.612653   3.586705   15.00
waist_to_hip_ratio                  100000.0    0.856078   0.046837    0.67
systolic_bp                         100000.0  115.799610  14.284073   90.00
diastolic_bp                        100000.0   75.232490   8.204250   50.00
heart_rate                          100000.0   69.632870   8.371954   40.00
cholesterol_total                   100000.0  185.978110  32.013005  100.00
hdl_cholesterol                     100000.0   54.042790  10.267374   20.00
ldl_cholesterol                     100000.0  103.000430  33.390256   50.00
triglycerides                       100000.0  121.462650  43.372619   30.00
glucose_fasting                     100000.0  111.117120  13.595610   60.00
glucose_postprandial                100000.0  160.035050  30.935472   70.00
insulin_level                       100000.0    9.061242   4.954060    2.00
hba1c                               100000.0    6.520776   0.813921    4.00
diabetes_risk_score                 100000.0   30.222362   9.061505    2.70
diagnosed_diabetes                  100000.0    0.599980   0.489904    0.00

                                       25%     50%     75%     max
age                                  39.00   50.00   61.00   90.00
alcohol_consumption_per_week          1.00    2.00    3.00   10.00
physical_activity_minutes_per_week   57.00  100.00  160.00  833.00
diet_score                            4.80    6.00    7.20   10.00
sleep_hours_per_day                   6.30    7.00    7.70   10.00
screen_time_hours_per_day             4.30    6.00    7.70   16.80
family_history_diabetes               0.00    0.00    0.00    1.00
hypertension_history                  0.00    0.00    1.00    1.00
cardiovascular_history                0.00    0.00    0.00    1.00
bmi                                  23.20   25.60   28.00   39.20
waist_to_hip_ratio                    0.82    0.86    0.89    1.06
systolic_bp                         106.00  116.00  125.00  179.00
diastolic_bp                         70.00   75.00   81.00  110.00
heart_rate                           64.00   70.00   75.00  105.00
cholesterol_total                   164.00  186.00  208.00  318.00
hdl_cholesterol                      47.00   54.00   61.00   98.00
ldl_cholesterol                      78.00  102.00  126.00  263.00
triglycerides                        91.00  121.00  151.00  344.00
glucose_fasting                     102.00  111.00  120.00  172.00
glucose_postprandial                139.00  160.00  181.00  287.00
insulin_level                         5.09    8.79   12.45   32.22
hba1c                                 5.97    6.52    7.07    9.80
diabetes_risk_score                  23.80   29.00   35.60   67.20
diagnosed_diabetes                    0.00    1.00    1.00    1.00
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 31 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   age                                 100000 non-null  int64
 1   gender                              100000 non-null  object
 2   ethnicity                           100000 non-null  object
 3   education_level                     100000 non-null  object
 4   income_level                        100000 non-null  object
 5   employment_status                   100000 non-null  object
 6   smoking_status                      100000 non-null  object
 7   alcohol_consumption_per_week        100000 non-null  int64
 8   physical_activity_minutes_per_week  100000 non-null  int64
 9   diet_score                          100000 non-null  float64
 10  sleep_hours_per_day                 100000 non-null  float64
 11  screen_time_hours_per_day           100000 non-null  float64
 12  family_history_diabetes             100000 non-null  int64
 13  hypertension_history                100000 non-null  int64
 14  cardiovascular_history              100000 non-null  int64
 15  bmi                                 100000 non-null  float64
 16  waist_to_hip_ratio                  100000 non-null  float64
 17  systolic_bp                         100000 non-null  int64
 18  diastolic_bp                        100000 non-null  int64
 19  heart_rate                          100000 non-null  int64
 20  cholesterol_total                   100000 non-null  int64
 21  hdl_cholesterol                     100000 non-null  int64
 22  ldl_cholesterol                     100000 non-null  int64
 23  triglycerides                       100000 non-null  int64
 24  glucose_fasting                     100000 non-null  int64
 25  glucose_postprandial                100000 non-null  int64
 26  insulin_level                       100000 non-null  float64
 27  hba1c                               100000 non-null  float64
 28  diabetes_risk_score                 100000 non-null  float64
 29  diabetes_stage                      100000 non-null  object
 30  diagnosed_diabetes                  100000 non-null  int64
dtypes: float64(8), int64(16), object(7)
memory usage: 23.7+ MB
df.info: None

Many variables such as education level, gender are stored as strings, where as many boolean variables such as diabetes diagnosis and family history are values of 1 or 0. The average age in this dataset is 50, where 95% of the age distribution is covered by two SDs from 35 to 65 with min at 18 yo. 
### Chapter 2 - Series and Basic Array
- Write three tiny objects manually:
	1.	A Series of 5 ages.
	2.	A DataFrame with columns ["age","bmi"] and 4 rows.
	3.	A NumPy array of shape (3, 3) with numbers 0–8.

In [3]:
# Drill A
age_series = pd.Series([18, 39, 45, 74, 32], name="age")
df_sample = pd.DataFrame({
    "age": [39, 45, 74, 32],
    "bmi": [23, 26, 30, 19]
})
test_array = np.arange(0, 9).reshape(3, 3)

print(age_series)
print(df_sample)
print(test_array)

0    18
1    39
2    45
3    74
4    32
Name: age, dtype: int64
   age  bmi
0   39   23
1   45   26
2   74   30
3   32   19
[[0 1 2]
 [3 4 5]
 [6 7 8]]

**Drill B:**
- Using your diabetes dataset:
	1.	Create a Series s_bmi containing only the bmi column.
	2.	Get its .values, .index, and .dtype.
	3.	Convert it to a NumPy array explicitly.

In [4]:
s_bmi = df['bmi']

val = s_bmi.values
idx = s_bmi.index
type = s_bmi.dtype

bmi_array = np.array(s_bmi)

print(s_bmi.head())
print(val)
print(idx)
print(type)
print(bmi_array)

0    30.5
1    23.1
2    22.2
3    26.8
4    21.2
Name: bmi, dtype: float64
[30.5 23.1 22.2 ... 25.6 26.8 30.3]
RangeIndex(start=0, stop=100000, step=1)
float64
[30.5 23.1 22.2 ... 25.6 26.8 30.3]

**Drill C:**
- Construct a DataFrame manually representing just 3 patients with columns:
    1. ["age", "bmi", "glucose_fasting", "diagnosed_diabetes"]
    2. Fill with plausible but fake numbers.
    3. Then answer:
        - Which columns would you store as float?
        - Which would you store as category?
        - Which would require normalization or log transform?

In [5]:
mock_table = pd.DataFrame({
    "age": [34, 52, 59],
    "bmi": [30, 29, 25],
    "glucose_fasting": [100.0, 85.5, 113.0],
    "diagnosed_diabetes": [0, 1, 1]
})
mock_table

   age  bmi  glucose_fasting  diagnosed_diabetes
0   34   30            100.0                   0
1   52   29             85.5                   1
2   59   25            113.0                   1

*Answer:* 
- I stored glucose as float, but bmi should probably be float too. I would not store any of those as category. If you want to do dimensionality reduction then you'd have to normalize the numeric variables. Otherwise, none of those need to be log transformed since those variables shouldn't have extreme values in a normal distribution. But you can normalize any continuous and numeric features such as age, bmi and glucose. 
- Normalization (z score) is necessary for algorithms that is sensitive to the magnitude of the features, such as when doing singular value decomposition (k means, k nearest n, PCA). Normalization is commonly used before ML steps.

**Stretch Drill — Reconstruct a Subtable From df**
- Using your dataset, recreate this mini-table:
    1. Columns: ["age", "gender", "bmi", "diabetes_stage"]
    2. Pick rows 100 to 110.
    3. Then turn that slice into:
        1.	A dictionary of lists
        2.	A NumPy array
        3.	A new DataFrame

In [6]:
target_col = ["age", "gender", "bmi", "diabetes_stage"]
target_row = slice(100, 110)
df_subtable = df.loc[target_row, target_col]

df_subtable
# convert to dictionary

     age  gender   bmi diabetes_stage
100   27  Female  19.8         Type 2
101   43    Male  22.6   Pre-Diabetes
102   45  Female  27.6         Type 2
103   37  Female  22.3    No Diabetes
104   47  Female  23.7   Pre-Diabetes
105   56    Male  32.2         Type 2
106   80    Male  29.0         Type 2
107   53   Other  28.3    No Diabetes
108   54  Female  30.8         Type 2
109   49    Male  24.3   Pre-Diabetes
110   19    Male  20.1         Type 2

In [7]:
dict_of_list = df_subtable.to_dict('list')
import json
print(json.dumps(dict_of_list))

{"age": [27, 43, 45, 37, 47, 56, 80, 53, 54, 49, 19], "gender": ["Female", "Male", "Female", "Female", "Female", "Male", "Male", "Other", "Female", "Male", "Male"], "bmi": [19.8, 22.6, 27.6, 22.3, 23.7, 32.2, 29.0, 28.3, 30.8, 24.3, 20.1], "diabetes_stage": ["Type 2", "Pre-Diabetes", "Type 2", "No Diabetes", "Pre-Diabetes", "Type 2", "Type 2", "No Diabetes", "Type 2", "Pre-Diabetes", "Type 2"]}

In [8]:
numpy_array = df_subtable.to_numpy()
numpy_array

array([[27, 'Female', 19.8, 'Type 2'],
       [43, 'Male', 22.6, 'Pre-Diabetes'],
       [45, 'Female', 27.6, 'Type 2'],
       [37, 'Female', 22.3, 'No Diabetes'],
       [47, 'Female', 23.7, 'Pre-Diabetes'],
       [56, 'Male', 32.2, 'Type 2'],
       [80, 'Male', 29.0, 'Type 2'],
       [53, 'Other', 28.3, 'No Diabetes'],
       [54, 'Female', 30.8, 'Type 2'],
       [49, 'Male', 24.3, 'Pre-Diabetes'],
       [19, 'Male', 20.1, 'Type 2']], dtype=object)

In [9]:
# construct a new dataframe from numpy array
df_new = pd.DataFrame(data=numpy_array, columns=target_col)
df_new

   age  gender   bmi diabetes_stage
0   27  Female  19.8         Type 2
1   43    Male  22.6   Pre-Diabetes
2   45  Female  27.6         Type 2
3   37  Female  22.3    No Diabetes
4   47  Female  23.7   Pre-Diabetes
5   56    Male  32.2         Type 2
6   80    Male  29.0         Type 2
7   53   Other  28.3    No Diabetes
8   54  Female  30.8         Type 2
9   49    Male  24.3   Pre-Diabetes
10  19    Male  20.1         Type 2

### Chapter 3 - Indexing, Selection and iloc
- Core Drill B — Precise Indexing
	1.	Select rows where age > 60 and return only columns ["bmi", "hba1c"].
	2.	Select every 5000th row.
	3.	Select rows 200–210 and columns 10–15 via .iloc.

In [10]:
target_col = ["bmi", "hba1c"]
over_60 = df.loc[df["age"] > 60, target_col]

every_5000 = over_60.iloc[::5000]

row_200 = df.iloc[200:210, 10:15]

row_200

,sleep_hours_per_day,screen_time_hours_per_day,family_history_diabetes,hypertension_history,cardiovascular_history
200,6.9,2.5,0,1,0
201,6.4,10.2,1,1,0
202,6.7,7.7,0,1,0
203,6.0,7.1,0,0,1
204,7.8,3.9,0,0,0
205,7.5,4.8,1,0,0
206,7.9,11.3,0,1,0
207,7.1,4.4,1,0,0
208,6.4,3.2,0,0,0
209,6.8,4.6,0,1,0

**Core Drill C**
- Multi-Condition Filters, construct these three filters:
	1.	Patients with bmi > 30 AND diagnosed diabetes = 1
	2.	Patients with hypertension_history == 1 OR cardiovascular_history == 1
	3.	Patients with ethnicity not in [“White”,“Asian”]

In [11]:
filtered_df1 = df.loc[(df["bmi"] > 30) & (df["diagnosed_diabetes"] == 1)]

filtered_df2 = df.loc[(df["hypertension_history"] == 1) | (df["cardiovascular_history"] == 1)]

filtered_df3 = df.loc[~df["ethnicity"].isin(["White", "Asian"])]

**Drill — Create a Subset View**
 - df_elderly_highrisk = df.loc[(df["age"] > 65) & (df["diabetes_risk_score"] > 0.7)]
    1. How many rows?
    2. What % of dataset?
    3. Which columns would you keep for an RA investigation?

In [12]:
df_elderly_highrisk = df.loc[(df["age"] > 65) & (df["diabetes_risk_score"] > 0.7)]

num_row = len(df_elderly_highrisk)
print(f"Number of rows: {num_row}")
total_row = len(df)
pct_row = num_row / total_row * 100
print(f"Percentage of rows: {pct_row:.2f}%")

Number of rows: 16731
Percentage of rows: 16.73%

### DAY 4 — Filtering, Boolean Masks, isin, negation
**Drill A — Boolean Mask Construction**
1.	Find all patients with abnormal fasting glucose > 125.
2.	Filter to those who:
    - exercise < 30 min/week
    - AND sleep < 6 hours
    - AND screen time > 6 hours
3.	Select people with BMI in the top 1% (hint: use .quantile())

In [13]:
abnormal = df.loc[df["glucose_fasting"] > 125]
print(len(abnormal))

filtered_abnormal = abnormal.loc[(abnormal["physical_activity_minutes_per_week"] < 30.0)
                                 & (abnormal["sleep_hours_per_day"] < 6.0)
                                 & (abnormal["screen_time_hours_per_day"] > 6.0)]

bmi_threshold = filtered_abnormal["bmi"].quantile(0.99)
top_1 = filtered_abnormal.loc[filtered_abnormal["bmi"] >= bmi_threshold]

print(len(top_1))

14528
2

**Drill C — Multi-Column Outliers**
- Define “metabolic extreme” as:
    1. bmi > 35
    2. triglycerides > 250
    3. hba1c > 6.5

- Construct the boolean mask explicitly, inspect the subset, and report:
    1. Count
    2. Mean age
    3. Gender distribution

In [14]:
mask = (df["bmi"] > 35) & (df["triglycerides"] > 250) & (df["hba1c"] > 6.5)
met_extreme = df[mask]

print(f"Count of metabolic extreme: {len(met_extreme)}")
mean_age = met_extreme['age'].mean()
print(f"Mean age: {mean_age:.2f}")

female = met_extreme.loc[met_extreme['gender'] == "Female"]
male = met_extreme.loc[met_extreme['gender'] == "Male"]
pct_female = len(female) / len(met_extreme) * 100
pct_male = len(male) / len(met_extreme) * 100
print(f"Female distribution: {pct_female:.2f}%")
print(f"Male: {pct_male:.2f}%")

Count of metabolic extreme: 9
Mean age: 64.22
Female distribution: 77.78%
Male: 22.22%

**Stretch Drill — Inversion & Set Logic**
- Perform:
	1.	Obtain rows where education_level is NOT in the top 3 most common categories.
	2.	Exclude individuals diagnosed with diabetes but keep only high-risk undiagnosed adults.
	3.	Compare their mean glucose_fasting to the full population.

In [15]:
top_3_edu = df['education_level'].value_counts().nlargest(3).index
top_3_edu

not_top3 = df.loc[~df['education_level'].isin(top_3_edu)]

mask = (not_top3['diagnosed_diabetes'] == 0) & (not_top3['diabetes_risk_score'] > 0.75)
subset_df = not_top3.loc[mask]

subset_glucose = subset_df['glucose_fasting'].mean()
full_glucose = df['glucose_fasting'].mean()

print(f"Subset glucose: {subset_glucose:.2f}")
print(f"Population Glucose: {full_glucose:.2f}")

Subset glucose: 102.65
Population Glucose: 111.12

### Day 5 - Missing Data Diagnosis & Handling (NaNs)
**Drill A**
- answer using code + mental reasoning:
	1.	Count NaNs in each affected column. 
	2.	Compute % missing.
	3.	Identify whether missingness overlaps (same rows missing both).

In [16]:
df_na = df.copy()

idx = np.random.choice(df_na.index, size=5000, replace=False)
df_na.loc[idx, "bmi"] = np.nan

idx2 = np.random.choice(df_na.index, size=3000, replace=False)
df_na.loc[idx2, "hba1c"] = np.nan

In [17]:
# count nan in each column 
missing_count1 = df_na['bmi'].isna().sum()
missing_count2 = df_na['hba1c'].isna().sum()

total_row = len(df_na)
pct_missing1 = missing_count1 / total_row * 100
pct_missing2 = missing_count2 / total_row * 100

print(f"BMI column missing is {missing_count1} and HBA1C column missing is {missing_count2}")
print(f"BMI column missing percentage: {pct_missing1:.2f}%, HBA1C column missing percentage: {pct_missing2:.2f}%")

overlap = (df_na['bmi'].isna()) & (df_na['hba1c'].isna()).sum()
print(len(overlap))

BMI column missing is 5000 and HBA1C column missing is 3000
BMI column missing percentage: 5.00%, HBA1C column missing percentage: 3.00%
100000

**Core Drill B — Handling Missing Data**
- Perform three different fills:
	1.	Mean imputation for bmi.
	2.	Median imputation for hba1c.
	3.	Constant imputation for sleep_hours_per_day (e.g., fill with 7 but explain why this is risky).

In [18]:
bmi_mean = df_na['bmi'].mean()
hba1c_median = df_na['hba1c'].median()

df_na['bmi'] = df_na['bmi'].fillna(bmi_mean)
df_na['hba1c'] = df_na['hba1c'].fillna(hba1c_median)
df_na['sleep_hours_per_day'] = df_na['sleep_hours_per_day'].fillna(7) # risky b/c it introduces bias and changes the distribution/variance of the variable

**Core Drill C — Conditional Imputation**
- Impute BMI only for:
	- age > 60
	- gender == “Female”
		- Use df.loc[...] selection + .fillna().

In [19]:
impute_mask = (df_na['age'] > 60) & (df_na['gender'] == 'Female')
df_na.loc[impute_mask, 'bmi'] = df_na.loc[impute_mask, 'bmi'].fillna(bmi_mean)

print(f"NaNs after conditional imputation: {df_na['bmi'].isna().sum()}")

NaNs after conditional imputation: 0

**Stretch Drill — Missingness Pattern Analysis**
- Compute:
	- Correlation between missing bmi and high diabetes_risk_score.
	- Distribution of missing vs non-missing groups.

In [20]:
missing_mask = df_na['bmi'].isna()
missing_correlation = missing_mask.corr(df_na['diabetes_risk_score'])
print(f"correlation betwene misisng bmi and diabetes risk : {missing_correlation}")

df_na['missing_flag'] =  df_na['bmi'].isna()
distribution_missing = df_na.groupby('missing_flag')['diabetes_risk_score'].describe()

print("Distribution of missing vs. non-missing\n")
print(distribution_missing)

correlation betwene misisng bmi and diabetes risk : nan
Distribution of missing vs. non-missing

                 count       mean       std  min   25%   50%   75%   max
missing_flag
False         100000.0  30.222362  9.061505  2.7  23.8  29.0  35.6  67.2

/Users/gavinqu/dev/predoc/venv/lib/python3.14/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Users/gavinqu/dev/predoc/venv/lib/python3.14/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

### DAY 6 — Data Types, Conversion, Categorical Encoding, Duplicates
**Core Drill A — Type Conversion Drills**
- Do the following transformations:

    1. Convert education_level, ethnicity, and diabetes_stage → category.

    2. Convert cholesterol_total → float.

    3. Convert diagnosed_diabetes → boolean (True/False).

In [21]:
transformed = ['education_level', 'ethnicity', 'diabetes_stage']
df[transformed] = df[transformed].astype('category')

df['cholesterol_total'] = df['cholesterol_total'].astype(float)
df['diagnosed_diabetes'] = df['diagnosed_diabetes'].astype(bool)

# verification
print(df[['education_level', 'ethnicity', 'diabetes_stage','cholesterol_total', 'diagnosed_diabetes']].dtypes)

education_level       category
ethnicity             category
diabetes_stage        category
cholesterol_total      float64
diagnosed_diabetes        bool
dtype: object

**Core Drill B — Detect and Remove Duplicates**
- Simulate duplicates:

```df_dup = pd.concat([df.iloc[:2000], df.iloc[:2000]])  # 2000 duplicates```

1. Count duplicates via .duplicated().sum().

2. Drop duplicates via drop_duplicates().

3. Verify shapes before/after.

In [22]:
df_dup = pd.concat([df.loc[:2000], df.iloc[:2000]])

dup_count = df_dup.duplicated().sum()
print(f"Total Duplicates Before: {dup_count}\n Shape: {df_dup.shape}")

df_unique = df_dup.drop_duplicates()
print(f"Shape after dropping duplicates: {df_unique.shape}")

Total Duplicates Before: 2000
 Shape: (4001, 31)
Shape after dropping duplicates: (2001, 31)

**Core Drill C — Identify Mismatched Types**

- Produce a table of suspected type issues:
    1. Example checks:

    2. Columns with dtype object but only numeric contents

    3. Columns where unique() count is huge → convert to category?

    4. Columns where dtype is float but values are integers → downcast?

### DAY 7 — Groupby, Aggregation, Multi-Agg, Custom Functions
**Core Drill A — Basic Aggregations**
- Compute in one line each:

1. Mean BMI by gender
2. Median triglycerides by ethnicity
3. Count of diagnosed diabetics by age group (use cut/bins)

In [23]:
mean_bmi_by_gender = df.groupby('gender')['bmi'].mean()

median_triglyceride_by_eth = df.groupby('ethnicity')['triglycerides'].median()

bins = [0, 13, 18, 65, 100]
labels = ['Child', 'Teenager', 'Adult', 'Senior']
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, right=False)

count_diagnosed_by_age = df.groupby('age_group')['diagnosed_diabetes'].count()

print(f"Mean BMI by gender: {mean_bmi_by_gender}")
print(f"Median tryglyceride by ethnicity: {median_triglyceride_by_eth}")
print(f"count of diagnosed diabetics by age: {count_diagnosed_by_age}")

Mean BMI by gender: gender
Female    25.627404
Male      25.601794
Other     25.502385
Name: bmi, dtype: float64
Median tryglyceride by ethnicity: ethnicity
Asian       122.0
Black       122.0
Hispanic    121.0
Other       121.0
White       121.0
Name: triglycerides, dtype: float64
count of diagnosed diabetics by age: age_group
Child           0
Teenager        0
Adult       81642
Senior      18358
Name: diagnosed_diabetes, dtype: int64

/var/folders/n2/8hz3y3r90rj63gkzgrl1hwg40000gn/T/ipykernel_21676/2491604048.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  median_triglyceride_by_eth = df.groupby('ethnicity')['triglycerides'].median()
/var/folders/n2/8hz3y3r90rj63gkzgrl1hwg40000gn/T/ipykernel_21676/2491604048.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  count_diagnosed_by_age = df.groupby('age_group')['diagnosed_diabetes'].count()

**Core Drill B — Multi-Aggregation**
- What is the resulting column index structure?
- How do you flatten the MultiIndex?

In [24]:
multi_agg_df = df.groupby("ethnicity").agg({
    "bmi": ["mean", "std"],
    "hba1c": ["mean", "max"],
    "cholesterol_total": "median"
})

cols = multi_agg_df.columns
multi_agg_df.columns = ['_'.join(col).strip() for col in cols]
print(multi_agg_df)

            bmi_mean   bmi_std  hba1c_mean  hba1c_max  \
ethnicity
Asian      25.576308  3.596816    6.520585       9.53
Black      25.642533  3.581136    6.525600       9.39
Hispanic   25.590330  3.612489    6.506666       9.40
Other      25.543216  3.569967    6.530370       9.46
White      25.628057  3.576479    6.524126       9.80

           cholesterol_total_median
ethnicity
Asian                         186.0
Black                         185.0
Hispanic                      186.0
Other                         185.0
White                         186.0

/var/folders/n2/8hz3y3r90rj63gkzgrl1hwg40000gn/T/ipykernel_21676/35147049.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  multi_agg_df = df.groupby("ethnicity").agg({

**Core Drill C — Custom Lambda Functions**
1. Coefficient of variation of BMI by ethnicity:
``lambda x: x.std() / x.mean()``
2. Percentage of population with diagnosed diabetes within each education level
3. Average metabolic “cluster score” via:
``(bmi + waist_to_hip_ratio + triglycerides)``

In [25]:
bmi_cv = df.groupby('ethnicity')['bmi'].agg(
    cv_bmi=lambda x: x.std() / x.mean()     # x is series of all bmi for each ethnic group
)

diabetes_pct = df.groupby('education_level')['diagnosed_diabetes'].agg(
    pct_diabetes=lambda x: (x.mean() * 100).round(2)
)

# create cluster score and aggregate for mean
df['meta_cluster_score'] = (
    df['bmi'] + df['waist_to_hip_ratio'] + df['triglycerides']
)
avg_meta_score = df.groupby('ethnicity')['meta_cluster_score'].mean()   
avg_metabolic = df.groupby('ethnicity')['meta_cluster_score'].agg(
    mean_meta_score=lambda x: x.mean()
)

print(bmi_cv)
print(diabetes_pct)
print(avg_meta_score)
print(avg_metabolic)

             cv_bmi
ethnicity
Asian      0.140631
Black      0.139656
Hispanic   0.141166
Other      0.139762
White      0.139553
                 pct_diabetes
education_level
Graduate                60.12
Highschool              60.07
No formal               60.45
Postgraduate            59.35
ethnicity
Asian       148.341079
Black       148.148102
Hispanic    147.150137
Other       147.862398
White       148.093495
Name: meta_cluster_score, dtype: float64
           mean_meta_score
ethnicity
Asian           148.341079
Black           148.148102
Hispanic        147.150137
Other           147.862398
White           148.093495

/var/folders/n2/8hz3y3r90rj63gkzgrl1hwg40000gn/T/ipykernel_21676/2761067556.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  bmi_cv = df.groupby('ethnicity')['bmi'].agg(
/var/folders/n2/8hz3y3r90rj63gkzgrl1hwg40000gn/T/ipykernel_21676/2761067556.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  diabetes_pct = df.groupby('education_level')['diagnosed_diabetes'].agg(
/var/folders/n2/8hz3y3r90rj63gkzgrl1hwg40000gn/T/ipykernel_21676/2761067556.py:13: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avg_meta_score = df.groupby('ethnicity')['meta_cluster_score'].mean()
/var/folders/n2/8hz3y3r90rj63gkzgrl1hwg40000gn/T/ipykernel_21676/2761067556.py:14: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avg_metabolic = df.groupby('ethnicity')['meta_cluster_score'].agg(

## DAY 8 — Pivot Tables, Crosstab, Reshaping for Summaries
**Core Drill A — Pivot Table Basics**
- Create:
1. Pivot: index = gender, columns = smoking_status, values = bmi (agg mean)
2. Pivot: index = ethnicity, columns = diabetes_stage, values = hba1c (agg median)
- Then:
    * Compare pivot results with equivalent groupby operations.
    * Verbalize which format gives clearer insights.

In [26]:
pivot_gender = df.pivot_table(index='gender', columns='smoking_status', values='bmi', aggfunc="mean")
pivot_ethnicity = df.pivot_table(index='ethnicity', columns='diabetes_stage', values='hba1c', aggfunc="median")

print(pivot_gender)
print("\n")
print(pivot_ethnicity)

gender_agg_df = df.groupby(['gender', 'smoking_status']).agg({"bmi": "mean"})
gender_agg_df

smoking_status    Current     Former      Never
gender
Female          25.595994  25.637489  25.634646
Male            25.555290  25.624338  25.609834
Other           25.616381  25.704103  25.399176


diabetes_stage  Gestational  No Diabetes  Pre-Diabetes  Type 1  Type 2
ethnicity
Asian                  6.43         5.31          6.06   6.030    6.94
Black                  6.62         5.27          6.06   6.140    6.96
Hispanic               6.55         5.27          6.06   6.650    6.94
Other                  6.63         5.30          6.07   6.035    6.95
White                  6.40         5.27          6.07   6.380    6.95

/var/folders/n2/8hz3y3r90rj63gkzgrl1hwg40000gn/T/ipykernel_21676/1071498843.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_ethnicity = df.pivot_table(index='ethnicity', columns='diabetes_stage', values='hba1c', aggfunc="median")

                             bmi
gender smoking_status
Female Current         25.595994
       Former          25.637489
       Never           25.634646
Male   Current         25.555290
       Former          25.624338
       Never           25.609834
Other  Current         25.616381
       Former          25.704103
       Never           25.399176

**Core Drill B — Crosstab Drills**
- Compute:
    1. ``pd.crosstab(df.gender, df.diagnosed_diabetes)``
    2. Normalize by rows
    3. Convert counts → percentages

In [27]:
cross_tab = pd.crosstab(df.gender, df.diagnosed_diabetes, normalize=0) # 'index', 'columns', 0 or 1
cross_tab

diagnosed_diabetes     False     True
gender
Female              0.401545  0.598455
Male                0.399343  0.600657
Other               0.378043  0.621957

**Core Drill C — Advanced Reshaping**
- Pick a pivot table from above and:
1. stack() → long format
2. reset_index()
3. rename columns to remove MultiIndex
4. Filter out any cells with < 50 observations

In [28]:
df_long = pivot_gender.stack().reset_index()
df_long.rename(columns={'bmi': 'mean_bmi'}, inplace=True)
df_long

   gender smoking_status          0
0  Female        Current  25.595994
1  Female         Former  25.637489
2  Female          Never  25.634646
3    Male        Current  25.555290
4    Male         Former  25.624338
5    Male          Never  25.609834
6   Other        Current  25.616381
7   Other         Former  25.704103
8   Other          Never  25.399176

## Day 9 - Merge & Join
**Core Drill A - Build Synthetic Tables**

In [29]:
demo_cols = ['age', 'gender', 'ethnicity','education_level', 'income_level','diagnosed_diabetes']
df_demo = df[demo_cols]

biomarker_cols = ['age', 'bmi', 'hba1c','glucose_fasting','diabetes_risk_score']
df_biomarkers = df[biomarker_cols]

**Core Drill B — Join Semantics**
- Perform the following joins and predict row counts before running:
1. Inner join on age
2. Left join (df_demo left)
3. Outer join
- Then answer verbally:
* Why do row counts explode?
* Why is age a bad merge key?
* What would be a better surrogate key in real data?

In [30]:
# df_inner = pd.merge(df_demo, df_biomarkers, on='age', how='inner')
# df_left = pd.merge(df_demo, df_biomarkers, on='age', how='left')
# df_outer = pd.merge(df_demo, df_biomarkers, on='age', how='outer')

* explosion happens because age is not unique, therefore every instance of age 30 in demo_df will create every possible combinations of demo and biomarker n x m rows. 
* age is a bad merge key because it's non-unique you lose the one-to-one aspect of joining data, leading to duplicates. we would also get artificially small standard errors and have artificially small p-values. I would use a unique identifier creating a patient_id if it does not already exists.

**Core Drill C — Merge Diagnostics**
- Intentionally create a faulty merge and diagnose it:
* Check duplicated keys pre-merge
* Use _merge=True
* Identify orphaned rows

In [31]:
# check if age is unique first 
print(f"is age unique in demo_df? {df_demo['age'].is_unique}")
print(f"is age unique in biomarker? {df_biomarkers['age'].is_unique}")
print(df_demo['age'].value_counts().head())

is age unique in demo_df? False
is age unique in biomarker? False
age
52    2517
51    2510
49    2494
53    2482
50    2476
Name: count, dtype: int64

In [32]:
df_diagnose = pd.merge(
    df_demo,
    df_biomarkers,
    on='age',
    how='outer', 
    indicator=True
)

print(df_diagnose['_merge'].value_counts())     # _merge added via indicator parameter

_merge
both          182083132
left_only             0
right_only            0
Name: count, dtype: int64

## Day 10 - concat, stack, unstack, shape, transform
**Core Drill A - Vertical vs. Horizontal Concat**
- Create two subsets:
* `df_lifestyle: smoking, alcohol, exercise, sleep`
* `df_vitals: bp, cholesterol, glucose, bmi`
- Perform:
1. Row-wise concat (axis=0)
2. Column-wise concat (axis=1)